// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import SmileOutlined from '/Users/baiyunpeng04/workspace/stock/stock-frontend/node_modules/@ant-design/icons/es/icons/SmileOutlined';
import BulbOutlined from '/Users/baiyunpeng04/workspace/stock/stock-frontend/node_modules/@ant-design/icons/es/icons/BulbOutlined';
import ToolOutlined from '/Users/baiyunpeng04/workspace/stock/stock-frontend/node_modules/@ant-design/icons/es/icons/ToolOutlined';
export default { SmileOutlined, BulbOutlined, ToolOutlined };
